# Site settings

# REQUIRED CHANGES
# Edit next line, providing your own name.
title: tsumjoy | mission-matching index
# Edit next line, replacing 'techfolios' with your github username
url: "https://tsumjoy.github.io"
# Edit next line so that baseurl is "" if your repo is <username>.github.io
baseurl: ""

# OPTIONAL CHANGES
# You might want to change the bio page label to something else, such as CV
missions-page-label: "missions: {"
# You might want to change the theme associated with one or more sections of the site.
# Defining your own custom theme variations is easy. See the documentation.
theme-home: theme-home-builtin-1.html

theme-tsumtsum: theme-tsumtsum-builtin-1.html
theme-internationalcollection: theme-international-collection-builtin-1.html
theme-japancollection: theme-japan-collection-builtin-1.html

theme-missions: theme-missions-builtin-1.html
theme-mission-gender: theme-missions-gender-builtin-1.html
theme-mission-gender-boy: theme-missions-gender-boy-builtin-1.html
theme-mission-gender-boy-international: theme-missions-gender-boy-international-builtin-1.html
theme-mission-gender-boy-japan: theme-missions-gender-boy-japan-builtin-1.html
theme-mission-gender-girl: theme-missions-gender-girl-builtin-1.html
theme-mission-gender-girl-international: theme-missions-gender-girl-international-builtin-1.html
theme-mission-gender-girl-japan: theme-missions-gender-girl-japan-builtin-1.html

theme-mission-color: theme-missions-color-builtin-1.html
theme-mission-color-red: theme-missions-color-red-builtin-1.html
theme-mission-color-red-international: theme-missions-color-red-international-builtin-1.html
theme-mission-color-red-japan: theme-missions-color-red-japan-builtin-1.html
theme-mission-color-yellow: theme-missions-color-yellow-builtin-1.html
theme-mission-color-yellow-international: theme-missions-color-yellow-international-builtin-1.html
theme-mission-color-yellow-japan: theme-missions-color-yellow-japan-builtin-1.html
theme-mission-color-green: theme-missions-color-green-builtin-1.html
theme-mission-color-green-international: theme-missions-color-green-international-builtin-1.html
theme-mission-color-green-japan: theme-missions-color-green-japan-builtin-1.html
theme-mission-color-blue: theme-missions-color-blue-builtin-1.html
theme-mission-color-blue-international: theme-missions-color-blue-international-builtin-1.html
theme-mission-color-blue-japan: theme-missions-color-blue-japan-builtin-1.html
theme-mission-color-purple: theme-missions-color-purple-builtin-1.html
theme-mission-color-purple-international: theme-missions-color-purple-international-builtin-1.html
theme-mission-color-purple-japan: theme-missions-color-purple-japan-builtin-1.html
theme-mission-color-black: theme-missions-color-black-builtin-1.html
theme-mission-color-black-international: theme-missions-color-black-international-builtin-1.html
theme-mission-color-black-japan: theme-missions-color-black-japan-builtin-1.html
theme-mission-color-brown: theme-missions-color-brown-builtin-1.html
theme-mission-color-brown-international: theme-missions-color-brown-international-builtin-1.html
theme-mission-color-brown-japan: theme-missions-color-brown-japan-builtin-1.html
theme-mission-color-white: theme-missions-color-white-builtin-1.html
theme-mission-color-white-international: theme-missions-color-white-international-builtin-1.html
theme-mission-color-white-japan: theme-missions-color-white-japan-builtin-1.html

theme-mission-series: theme-missions-series-builtin-1.html
theme-mission-series-mickeyandfriends: theme-missions-series-mickey-and-friends-builtin-1.html
theme-mission-series-mickeyandfriends-international: theme-missions-series-mickey-and-friends-international-builtin-1.html
theme-mission-series-mickeyandfriends-japan: theme-missions-series-mickey-and-friends-japan-builtin-1.html
theme-mission-series-chipndale: theme-missions-series-chip-n-dale-builtin-1.html
theme-mission-series-chipndale-international: theme-missions-series-chip-n-dale-international-builtin-1.html
theme-mission-series-chipndale-japan: theme-missions-series-chip-n-dale-japan-builtin-1.html
theme-mission-series-winniethepooh: theme-missions-series-winnie-the-pooh-builtin-1.html
theme-mission-series-winniethepooh-international: theme-missions-series-winnie-the-pooh-international-builtin-1.html
theme-mission-series-winniethepooh-japan: theme-missions-series-winnie-the-pooh-japan-builtin-1.html
theme-mission-series-aladdin: theme-missions-series-aladdin-builtin-1.html
theme-mission-series-aladdin-international: theme-missions-series-aladdin-international-builtin-1.html
theme-mission-series-aladdin-japan: theme-missions-series-aladdin-japan-builtin-1.html
theme-mission-series-beautyandthebeast: theme-missions-series-beauty-and-the-beast-builtin-1.html
theme-mission-series-beautyandthebeast-international: theme-missions-series-beauty-and-the-beast-international-builtin-1.html
theme-mission-series-beautyandthebeast-japan: theme-missions-series-beauty-and-the-beast-japan-builtin-1.html
theme-mission-series-littlemermaid: theme-missions-series-little-mermaid-builtin-1.html
theme-mission-series-littlemermaid-international: theme-missions-series-little-mermaid-international-builtin-1.html
theme-mission-series-littlemermaid-japan: theme-missions-series-little-mermaid-japan-builtin-1.html
theme-mission-series-tangled: theme-missions-series-tangled-builtin-1.html
theme-mission-series-tangled-international: theme-missions-series-tangled-international-builtin-1.html
theme-mission-series-tangled-japan: theme-missions-series-tangled-japan-builtin-1.html
theme-mission-series-frozen: theme-missions-series-frozen-builtin-1.html
theme-mission-series-frozen-international: theme-missions-series-frozen-international-builtin-1.html
theme-mission-series-frozen-japan: theme-missions-series-frozen-japan-builtin-1.html
theme-mission-series-bambi: theme-missions-series-bambi-builtin-1.html
theme-mission-series-bambi-international: theme-missions-series-bambi-international-builtin-1.html
theme-mission-series-bambi-japan: theme-missions-series-bambi-japan-builtin-1.html
theme-mission-series-lionking: theme-missions-series-lion-king-builtin-1.html
theme-mission-series-lionking-international: theme-missions-series-lion-king-international-builtin-1.html
theme-mission-series-lionking-japan: theme-missions-series-lion-king-japan-builtin-1.html
theme-mission-series-liloandstitch: theme-missions-series-lilo-and-stitch-builtin-1.html
theme-mission-series-liloandstitch-international: theme-missions-series-lilo-and-stitch-international-builtin-1.html
theme-mission-series-liloandstitch-japan: theme-missions-series-lilo-and-stitch-japan-builtin-1.html
theme-mission-series-aliceinwonderland: theme-missions-series-alice-in-wonderland-builtin-1.html
theme-mission-series-aliceinwonderland-international: theme-missions-series-alice-in-wonderland-international-builtin-1.html
theme-mission-series-aliceinwonderland-japan: theme-missions-series-alice-in-wonderland-japan-builtin-1.html
theme-mission-series-zootopia: theme-missions-series-zootopia-builtin-1.html
theme-mission-series-zootopia-international: theme-missions-series-zootopia-international-builtin-1.html
theme-mission-series-zootopia-japan: theme-missions-series-zootopia-japan-builtin-1.html
theme-mission-series-pixar: theme-missions-series-pixar-builtin-1.html
theme-mission-series-pixar-international: theme-missions-series-pixar-international-builtin-1.html
theme-mission-series-pixar-japan: theme-missions-series-pixar-japan-builtin-1.html
theme-mission-series-toystory: theme-missions-series-toy-story-builtin-1.html
theme-mission-series-toystory-international: theme-missions-series-toy-story-international-builtin-1.html
theme-mission-series-toystory-japan: theme-missions-series-toy-story-japan-builtin-1.html
theme-mission-series-monstersinc: theme-missions-series-monsters-inc-builtin-1.html
theme-mission-series-monstersinc-international: theme-missions-series-monsters-inc-international-builtin-1.html
theme-mission-series-monstersinc-japan: theme-missions-series-monsters-inc-japan-builtin-1.html
theme-mission-series-starwars: theme-missions-series-star-wars-builtin-1.html
theme-mission-series-starwars-international: theme-missions-series-star-wars-international-builtin-1.html
theme-mission-series-starwars-japan: theme-missions-series-star-wars-japan-builtin-1.html
theme-mission-series-marvel: theme-missions-series-marvel-builtin-1.html
theme-mission-series-marvel-international: theme-missions-series-marvel-international-builtin-1.html
theme-mission-series-marvel-japan: theme-missions-series-marvel-japan-builtin-1.html
theme-mission-series-kingdomhearts: theme-missions-series-kingdomhearts-builtin-1.html
theme-mission-series-kingdomhearts-international: theme-missions-series-kingdomhearts-international-builtin-1.html
theme-mission-series-kingdomhearts-japan: theme-missions-series-kingdomhearts-japan-builtin-1.html


theme-bio: theme-bio-builtin-1.html

# Specify the rouge syntax highlighter theme. Pick one from css/rouge.
rouge-theme: igorpro

# YOU NORMALLY NEVER CHANGE THE FOLLOWING
markdown: kramdown
include: [_data]

